export const MsgType={
  TAB_ADD: 'TAB_ADD',
  MENU_HIGHLIGHT: 'MENU_HIGHLIGHT',
  TAB_TITLE: 'TAB_TITLE',
  ROUTER_CHANGE: 'ROUTER_CHANGE',
  TABS_HIDE: 'TABS_HIDE',
  TAB_REMOVE: 'TAB_REMOVE',
  TAB_REFRESH: 'TAB_REFRESH',
  TAB_CLEAR: 'TAB_CLEAR',
  LOGO_UPDATE: 'LOGO_UPDATE',
};
